server:
  port: 8080

logging:
  config: classpath:log4j2.xml

#数据源配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/cangku?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 20
      max-wait: 3000
      initial-size: 5
      filters: stat,wall
      validation-query: select 1
      enable: true
      #监控页面配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
  devtools:
    restart:
      enabled: true #设置开启热部署
  thymeleaf:
    cache: false #页面不加载缓存
    enabled: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  redis:
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        #连接池最大的闲置连接数
#        max-idle: 20
#        #连接池最大的连接数
#        max-active: 100
#        #连接池最小的闲置连接数
#        min-idle: 10


debug: true

#mybatis-plus配置
mybatis-plus:
  mapper-locations:
  - classpath*:mapping/*/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro配置
#shiro:
#  hash-algorithm-name: md5
#  hash-iterations: 2
#  anon-urls:
#  - /index.html
#  - /sys/toLogin*
#  - /resources/**
#  - /login/login*
#  - /login/getValidCode*
#  login-url: /index.html
#  log-out-url: /login/logout*
#  authc-urls:
#  - /**


